### PR TITLE
update job that builds against upstream master

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by pepijnve** [comment]
Changing the ordering made bundler use asciidoctor 1.5.6 again instead of the version from master. Your version has this in the build log:

```
12.38s$ bundle install --path vendor/bundle --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using asciidoctor 1.5.6
Using rspec-support 3.6.0
...
```

The current master build has

```
bundle install --path vendor/bundle --jobs=3 --retry=3
Fetching https://github.com/asciidoctor/asciidoctor
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Using asciidoctor 1.5.7.dev from https://github.com/asciidoctor/asciidoctor (at master@68d6d26)
Fetching rake 12.0.0
Fetching rspec-support 3.6.0
Installing rspec-support 3.6.0
Installing rake 12.0.0
Fetching diff-lcs 1.3
Using bundler 1.15.1
Installing diff-lcs 1.3
NoMethodError: undefined method `requirements' for nil:NilClass
An error occurred while installing asciidoctor (1.5.7.dev), and
Bundler cannot continue.
```

So I think you side stepped the problem by implicitly using the latest released version of asciidoctor rather than fixed the issue with the master version from git. The latest released version builds are working on the current master build as well; it's only the jruby 1.7.9 + asciidoctor master combination that's failing with the above error for some reason.

**Comment by mojavelinux** [comment]
Actually, that was my mistake. I thought I could override the BUNDLE_GEMFILE environment variable, but Travis comes behind and overwrites it. So it's back to using the gemfile key in the configuration.

Now it works, and it builds with 1.5.7.dev.

https://travis-ci.org/asciidoctor/asciidoctor-diagram/builds/253486359

I'm confident that the gemspec must come first in the Gemfile.

**Comment by pepijnve** [comment]
Ok I'll have a look later today. Odd that it works just fine with the MRIs though and not with JRuby. If the order of directives mattered I would expect bundled to fail with MRI as well.

**Comment by mojavelinux** [comment]
It does not surprise me at all that there is some obscure bug in JRuby 1.7 ;)

**Comment by pepijnve** [comment]
@mojavelinux I flipped the `gem`/`gemspec` order on the master branch, but the build still fails on jruby 1.7 with the same error. jruby-head installs asciidoctor properly but has some failing tests that I need to look into.

**Comment by pepijnve** [comment]
Finally found it. Removing the `gem update --system` step did the trick. That was necessary at one point, but seems to have been made unnecessary in the meantime.
Now all that's left to do is figure out what's wrong with jruby-head. Something with their `open3` implementation again I think.

@mojavelinux I'm going to close this PR since I've integrated all the changes one by one on the master branch already. Thanks for your help in pinpointing the problem.

**Comment by mojavelinux** [comment]
> Finally found it. Removing the `gem update --system` step did the trick. 

That was my next guess. That's definitely not needed since we're using RVM. That would create some sort of hybrid Ruby environment, so the fault may not have even been with JRuby at all.

**Comment by mojavelinux** [comment]
Thanks for integrating these updates, Pepijn!

I'll go ahead and enable the triggered build from core now.

**Comment by mojavelinux** [comment]
> Now all that's left to do is figure out what's wrong with jruby-head. Something with their open3 implementation again I think.

I feel your pain ;)
